### ISSUE TITLE
Define defaults for extensions and targetExtensions

### ISSUE THREAD

**Issue by ppcano** [broccolijs/broccoli-filter#5]
Any extended BroccoliFilter must define its `extensions` property, otherwise it fails.

I guess, `extensions` are defined to be replaced with `targetExtension` because broccoli could not assure which is the real file extension with the [path api](http://nodejs.org/api/path.html#path_path_extname_p), but I think most of the FilterPlugins will not care about the final `targetExtension` because they are commonly used as temporary step of the final result.

I would add this default behaviour to avoid filter developers the need to define common `extensions` or force the plugin user to pass the extensions as `options` property.

**Comment by jonesetc** [comment]
@joliss Hopefully this isn't too dead, default behavior that I would propose:

- If extensions is not defined, run the filter on all files in the tree
- If the targetExtension is not defined, leave the extension alone (This seems to already be implemented)

The use case that I have for this, is that I am building a general purpose non-js file preprocessor. Each file in the inputTree would be mapped into a js file with it's contents available as a string. e.g. While using ember-data I could write shader files in `app/etc` with their native extension. Then the preprocessor would wrap that shader code in a JS module so that it could easily be imported by my component which has some three.js rendering inside of it. I would use this for many different types though, so ideally I would just give it the `app/etc` tree and let it transform all files.

If this is acceptable for the goals of this package let me know and I'll open a PR.

Thanks

**Comment by joliss** [comment]
@jonesetc I'm a bit hesitant to add this behavior for `extensions` and `targetExtensions`, but you can override [`getDestFilePath`](https://github.com/broccolijs/broccoli-filter/blob/900e9983c86e117393bac2b9f44464373e9f4cfb/index.js#L61) in your subclass to get that behavior.

**Comment by jonesetc** [comment]
Loud and clear. Alternatively would it be acceptable to give extensions a default of `[]`? That way the default behavior would not do any modifications but would also not throw an exception. It follows with the current implementation of no targetExtension passed in means that the extensions should not be altered.

**Comment by joliss** [comment]
> the default behavior would not do any modifications

Hm, so you're suggesting that it just pass everything through by default? Is there a use case for that?

**Comment by jonesetc** [comment]
My use case would be that if my ember-cli add-on is installed but no extensions specified, it would not affect the build. Currently I just default it to `[]` myself, so it's not required from broccoli-filter.

Mostly it's a matter of preference. I believe it makes more sense for it to do nothing by default rather than throw an exception by default.
